services:
  php:
    container_name: php
    build: .docker/php
    volumes:
      # App
      - ./app/:/app/
      # Data
      - ./data/:/data/
      #- ./logs/:/logs/
      # Dev
      - ./.docker/php/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

      - ./.docker/php/os/adm/:/adm/
      - ./.docker/php/os/docker/:/docker/
    ports:
      - "80:80"