services:
  web:
    container_name: ${COMPOSE_PREFIX}web
    build: ./.docker/web
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/web/os/docker/:/docker/
      - ./.docker/web/os/adm/:/adm/
      - ./.docker/web/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./.docker/web/apache/conf.d:/etc/apache2/conf.d
      - ./.docker/web/php/php.ini:/etc/php81/php.ini
      # Application
      - ./src/:/app/
    ports:
      # Web Server
      - "80:80"
      - "443:443"
      # XDebug
      - "10000:10000"