services:
  alpine:
    container_name: alpine
    build: ./.docker/alpine
    #volumes:
    #  - ./data/:/data/
    #  - ./logs/:/logs/
    #  - ./.docker/alpine/adm/:/adm/
    #  - ./.docker/alpine/docker/:/docker/