services:
  debian:
    container_name: ${COMPOSE_PREFIX}debian
    build: .docker/debian
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/debian/os/root/.bashrc:/root/.bashrc
      - ./.docker/debian/os/docker/:/docker/
      - ./.docker/debian/os/adm/:/adm/