services:
  php:
    container_name: ${COMPOSE_PREFIX}php
    build: ./.docker/php
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/php/os/docker/:/docker/
      - ./.docker/php/os/adm/:/adm/
      # Application
      - ./src/:/app/