services:
  alpine:
    image: f4lk0n/fkn:alpine3.20
    container_name: ${COMPOSE_PREFIX}alpine3.20
    hostname: alpine
    build:
      context: ./.docker/alpine
    networks:
      backend:
        ipv4_address: 173.3.20.20
      frontend:
        ipv4_address: 174.3.20.20
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Container
      - ./.docker/alpine/usr/local/bin/:/usr/local/bin/
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/

networks:
  backend:
    driver: bridge
    name: ${COMPOSE_PREFIX}backend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 173.3.20.0/16
          gateway: 173.3.20.1
  frontend:
    driver: bridge
    name: ${COMPOSE_PREFIX}frontend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 174.3.20.0/16
          gateway: 174.3.20.1