services:
  phalcon:
    container_name: ${COMPOSE_PREFIX}phalcon
    build: ./.docker/phalcon
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/phalcon/os/docker/:/docker/
      - ./.docker/phalcon/os/adm/:/adm/
      - ./.docker/phalcon/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./.docker/phalcon/php/php.ini:/etc/php81/php.ini
      # Application
      - ./src/:/app/
    ports:
      # Web Server
      - "80:80"
      - "443:443"
      # XDebug
      - "10000:10000"