services:
  alpine:
    container_name: ${COMPOSE_PREFIX}alpine
    build: ./.docker/alpine
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/alpine/os/docker/:/docker/
      - ./.docker/alpine/os/adm/:/adm/