services:
  alpine3.19:
    image: f4lk0n/fkn:alpine3.19
    container_name: ${COMPOSE_PREFIX}alpine3.19
    hostname: alpine
    build:
      context: ./.docker/alpine
    networks:
      backend:
        ipv4_address: 189.17.17.19
      frontend:
        ipv4_address: 189.11.11.19
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/
      - ./.docker/alpine/usr/local/bin/:/usr/local/bin/

networks:
  backend:
    driver: bridge
    name: ${COMPOSE_PREFIX}backend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 189.17.17.0/24
          gateway: 189.17.17.1
  frontend:
    driver: bridge
    name: ${COMPOSE_PREFIX}frontend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 189.11.11.0/24
          gateway: 189.11.11.1