version: '3'
services:
  mysql:
    container_name: mysql
    build: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      # Data
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    build: ./.docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend
  
  app:
    container_name: app
    build: ./.docker/app
    ports:
      - '80:8000'
    volumes:
      - './src:/app'
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
  