services:
  php8.2:
    image: f4lk0n/fkn:alpine3.20-apache2.4-php8.2
    container_name: ${COMPOSE_PREFIX}php8.2
    hostname: php8.2
    build:
      context: ./.docker/php
    networks:
      backend:
        ipv4_address: 189.17.17.82
      frontend:
        ipv4_address: 189.11.11.82
    ports:
      # Web Server
      - "80:80"
      - "443:443"
      # XDebug
      - "10000:10000"
    volumes:
      # Container
      - ./.docker/php/usr/local/bin/:/usr/local/bin/
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/

networks:
  backend:
    driver: bridge
    name: ${COMPOSE_PREFIX}backend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 189.17.17.0/24
          gateway: 189.17.17.1
  frontend:
    driver: bridge
    name: ${COMPOSE_PREFIX}frontend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 189.11.11.0/24
          gateway: 189.11.11.1