services:
  php:
    container_name: php
    build: .docker/php
    volumes:
      # App
      - ./app/:/app/
      # Data
      - ./data/:/data/
      #- ./logs/:/logs/
      # Dev
      - ./.docker/php/apache/apache2.conf:/etc/apache2/apache2.conf

      - ./.docker/php/os/adm/:/adm/
      - ./.docker/php/os/docker/:/docker/
    ports:
      - "80:80"