services:
  debian:
    image: f4lk0n/fkn:debian11
    container_name: ${COMPOSE_PREFIX}debian
    build:
      context: ./.docker/debian
      args:
        - ARG_HOST=debian
        - ARG_DOMAIN=${PROJECT_DOMAIN}
        - ARG_TIMEZONE=${PROJECT_TIMEZONE}
        - ARG_OS_APK_MIRROR=${DEBIAN_APK_MIRROR}
    networks:
      - frontend
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      
networks:
  frontend: