services:
  apache:
    container_name: apache
    build: ./.docker/apache
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      #- ./.docker/apache/adm/:/adm/
      - ./.docker/apache/docker/:/docker/
    ports:
      - "80:80"