services:
  web:
    container_name: ${COMPOSE_PREFIX}web
    build: ./.docker/web
    deploy:
      resources:
        limits:
          memory: 256M
    memswap_limit: 256M
    volumes:
      # Application
      - ./src/:/var/www/localhost/htdocs/
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Dev
      - ./.docker/web/os/docker/:/docker/
      - ./.docker/web/os/adm/:/adm/
      - ./.docker/web/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./.docker/web/apache/conf.d:/etc/apache2/conf.d
      - ./.docker/web/php/php.ini:/etc/php81/php.ini
    networks:
      - frontend
    ports:
      # Web Server
      - "80:80"
      - "443:443"
      # XDebug
      - "10000:10000"

networks:
  frontend: