services:
  debian:
    image: f4lk0n/fkn:debian11
    container_name: ${COMPOSE_PREFIX}debian
    hostname: debian
    build:
      context: ./.docker/debian
      args:
        - ARG_DOMAIN=${PROJECT_DOMAIN}
        - ARG_TIMEZONE=${PROJECT_TIMEZONE}
    networks:
      - frontend
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/
      
networks:
  frontend: