services:
  api:
    container_name: ${COMPOSE_PREFIX}api
    build: ./.docker/api
    deploy:
      resources:
        limits:
          memory: 256M
    memswap_limit: 256M
    volumes:
      # Application
      - ./src/:/var/www/localhost/htdocs/
      # Data
      - ./data/api/:/data/
      # Logs
      - ./logs/api/:/logs/
      # Dev
      - ./.docker/api/os/docker/:/docker/
      - ./.docker/api/os/adm/:/adm/
      - ./.docker/api/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./.docker/api/apache/conf.d:/etc/apache2/conf.d
      - ./.docker/api/php/php.ini:/etc/php81/php.ini
    ports:
      # API Server
      - "8080:8080"
      - "4430:4430"
      # XDebug
      - "10001:10001"