services:
  debian:
    container_name: debian
    build: .docker/debian
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/debian/os/adm/:/adm/
      - ./.docker/debian/os/docker/:/docker/