version: '3'
services:
  mysql:
    container_name: mysql
    build: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      # Data
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    build: ./.docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      # Config
      #- ./.docker/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  networks:
    backend: