services:
  alpine:
    image: f4lk0n/fkn:alpine3.19
    container_name: ${COMPOSE_PREFIX}alpine3.19
    hostname: alpine
    build:
      context: ./.docker/alpine
    networks:
      backend:
        ipv4_address: 172.20.0.20
      frontend:
        ipv4_address: 172.21.0.20
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/
      - ./.docker/alpine/usr/local/bin/:/usr/local/bin/

networks:
  backend:
    driver: bridge
    name: ${COMPOSE_PREFIX}backend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  frontend:
    driver: bridge
    name: ${COMPOSE_PREFIX}frontend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1