services:
  sql:
    image: f4lk0n/fkn:sql8
    container_name: ${COMPOSE_PREFIX}sql
    hostname: sql
    build: 
      context: ./.docker/sql
      args:
        - ARG_DOMAIN=${PROJECT_DOMAIN}
        - ARG_TIMEZONE=${PROJECT_TIMEZONE}
    networks:
      - backend
    #ports:
    #  - "3306:3306"
    volumes:
      # Data
      - ./data/sql:/data/sql
      # Logs
      - ./logs/sql:/logs/sql
      # Dev
      - ./.docker/sql/usr/local/bin/container-setup:/usr/local/bin/container-setup
      - ./.docker/sql/etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/sql/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  #sql-panel:
  #  image: f4lk0n/fkn:sql-panel
  #  container_name: ${COMPOSE_PREFIX}sql-panel
  #  hostname: sql-panel
  #  build: 
  #    context: ./.docker/sql-panel
  #    args:
  #      - ARG_DOMAIN=${PROJECT_DOMAIN}
  #      - ARG_TIMEZONE=${PROJECT_TIMEZONE}
  #  depends_on:
  #    - sql
  #  environment:
  #    - PMA_ARBITRARY=1
  #    - PMA_HOST=sql
  #    - PMA_PORT=3306
  #    - PMA_USER=root
  #    - PMA_PASSWORD=root
  #  ports:
  #    - "8081:80"
  #    - "8444:443"
  #  networks:
  #    - frontend
  #    - backend
  #  volumes:
  #    # Data
  #    - ./data/sql-panel:/data/sql-panel
  #    # Logs
  #    - ./logs/sql-panel:/logs/sql-panel

networks:
  frontend:
  backend: