services:
  alpine:
    container_name: ${COMPOSE_PREFIX}alpine
    build: 
      context: ./.docker/alpine
      args:
        - ARG_HOST=alpine
        - ARG_DOMAIN=${PROJECT_DOMAIN}
        - ARG_TIMEZONE=${PROJECT_TIMEZONE}
        - ARG_OS_APK_MIRROR=${ALPINE_APK_MIRROR}
    networks:
      - frontend
    #ports:
    #  - "hostPort:containerPort"
    volumes:
      # Data
      - ./data/:/data/
      # Logs
      - ./logs/:/logs/
      # Application
      - ./src/:/src/
networks:
  frontend: