services:
  apache:
    container_name: apache
    build: .docker/apache
    volumes:
      # Data
      - ./data/:/data/
      #- ./logs/:/logs/
      # Dev
      - ./.docker/apache/os/adm/:/adm/
      - ./.docker/apache/os/docker/:/docker/